### ISSUE TITLE
Incremental Font Transfer 2021-10-20

### ISSUE THREAD

**Issue by svgeesus** [w3c/security-request#16]
We have conducted a self-review of our spec [Incremental Font Transfer](https://www.w3.org/TR/IFT/), and the results can be found at https://github.com/w3c/IFT/issues/35 .

Please check our findings.

- Do you need a reply by a particular date?
No, we only just went to FPWD

Other comments:

**Comment by samuelweiler** [comment]
Requested review by @letoams

**Comment by samuelweiler** [comment]
@svgeesus , I see that you're citing the version of this spec in TR, not the editor's draft.  Which version would you like @letoams to review?  (n.b. I see that the editor's draft has a much-expanded privacy considerations section.  I haven't run a full diff, though.)

**Comment by svgeesus** [comment]
We get told off if we cite a non-TR spec for wide review, and current advice is to request early review on publication of FPWD.

But yes, please do in practice review the [Editors Draft](https://w3c.github.io/IFT/Overview.html)

**Comment by samuelweiler** [comment]
@svgeesus , thank you.  Indeed, for "reasons" we should be reviewing TR specs.

**Comment by svgeesus** [comment]
An [updated WD of IFT has been published](https://www.w3.org/TR/2022/WD-IFT-20220628/) which puts into one specification the Range Request and Patch-subset methods, and describes how client and server negotiate which method to use. Please base your review on this new /TR draft. Thanks!

**Comment by svgeesus** [comment]
14 months later, are there any security review comments?

**Comment by svgeesus** [comment]
A [new WD of IFT](https://www.w3.org/TR/2024/WD-IFT-20240709/) is available. This addresses review feedback from the earlier proposals. There is no longer a Range Request vs Patch Subset choice, and there is no longer any special protocol required. Compared to the earlier proposals, the risks of fingerprinting have been reduced and there should no longer be an impact on CDN caching.

Because this is a substantial rewrite, we have [a new Explainer](https://github.com/w3c/IFT/blob/main/IFT-Explainer.md)

A re-review from a Security perspective would be most welcome!

@simoneonofri

**Comment by svgeesus** [comment]
@simoneonofri I am guessing this request will wait for SING to be formed, right?

**Comment by simoneonofri** [comment]
> @simoneonofri I am guessing this request will wait for SING to be formed, right?

@svgeesus I've put it in the queue of things to do, surely when there's SING I'll be quicker to do them!

**Comment by svgeesus** [comment]
@simoneonofri we were waiting for this security review request to be handled before requesting TAG review. Given that it is now six months since review was requested on the latest WD, we intend to request TAG review _soon_, without waiting for security review to complete.
