### ISSUE TITLE
Web Share API  2021-??-?? > 2021-??-??

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/security-request#17]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Web Share API 
- URL of spec: https://www.w3.org/TR/web-share/

- Does your document have an in-line Security Considerations section, separate from Privacy Considerations? [yes](https://www.w3.org/TR/web-share/#security-and-privacy-considerations)
- What and when is your next expected transition? CR
- What has changed since any previous review? no previous review.
- Please point to the results of your own self-review: https://github.com/w3c/web-share/pull/150
- Where and how to file issues arising? https://github.com/w3c/web-share/issues
- Pointer to any explainer for the spec? https://github.com/w3c/web-share/blob/main/docs/explainer.md

Other comments:
We received review from the Privacy folks, but not sure if that covered security.

**Comment by samuelweiler** [comment]
> Does your document have an in-line Security Considerations section, separate from Privacy Considerations? yes

@marcoscaceres  This appears to be incorrect - the two are combined.

**Comment by samuelweiler** [comment]
Requested review by @richsalz

**Comment by samuelweiler** [comment]
Review complete.  https://github.com/w3c/web-share/issues/223. Thank you @richsalz!
