### ISSUE TITLE
[mediaqueries-5] Security and privacy self-review for `video-` prefixed media features 2021-12-09

### ISSUE THREAD

**Issue by willcassella** [w3c/security-request#19]
We have conducted a self-review of our spec [video-prefixed-features](https://www.w3.org/TR/mediaqueries-5/#video-prefixed-features), and the results can be found below.

**1) What information might this feature expose to Web sites or other parties, and for what purposes is that exposure necessary?**

In the case where a query containing `video-` prefixed media features (i.e., `video-dynamic-range`) returns a different result than a query containing equivalent non-prefixed features, this would expose the fact that the device has two rendering "planes", and is most likely a smart TV or dongle. This distinction is necessary for webpages capable of serving different content to both planes, as failing to distinguish between the two would result in either underestimating or overestimating the capabilities of the device for different types of content.

**2) Do features in your specification expose the minimum amount of information necessary to enable their intended uses?**

Yes. These prefixed features only exist in cases where the feature is worth distinguishing between the two planes, and otherwise are used identically to their non-prefixed counterparts.

**3) How do the features in your specification deal with personal information, personally-identifiable information (PII), or information derived from them?**

PII is not exposed.

**4) How do the features in your specification deal with sensitive information?**

Sensitive information is not exposed, either in the input or the output of these queries.

**5) Do the features in your specification introduce new state for an origin that persists across browsing sessions?**

No.

**6) Do the features in your specification expose information about the underlying platform to origins?**

Yes, these features could likely be used to identify the platform as a smart TV or dongle. This information does not change across origins and is rarely changing, though other than exposing the device as existing in this category, it's unlikely to expose more useful information than the regular set of media features.

**7) Does this specification allow an origin to send data to the underlying platform?**

No.

**8) Do features in this specification enable access to device sensors?**

No.

**9) What data do the features in this specification expose to an origin? Please also document what data is identical to data exposed by other features, in the same or different contexts.**

The data exposed is the result of using these media features in a media query, which may be different than the result of using the non-prefixed media features in a media query, though the shape of the data is indentical (a boolean).

**10) Do features in this specification enable new script execution/loading mechanisms?**

No.

**11) Do features in this specification allow an origin to access other devices?**

No.

**12) Do features in this specification allow an origin some measure of control over a user agent’s native UI?**

No.

**13) What temporary identifiers do the features in this specification create or expose to the web?**

There are no temporary identifiers exposed.

**14) How does this specification distinguish between behavior in first-party and third-party contexts?**

This feature does not distinguish between the two. This is useful for webpages embedding video content from other sites.

**15) How do the features in this specification work in the context of a browser’s Private Browsing or Incognito mode?**

The features work identically in private browsing mode to the regular browsing mode.

**16) Does this specification have both "Security Considerations" and "Privacy Considerations" sections?**

No.

**17) Do features in your specification enable origins to downgrade default security protections?**

No.

**18) How does your feature handle non-"fully active" documents?**

The `video-` prefixed media features used in media queries are handled identically to non-prefixed media features in non-"fully active" documents.

**19) What should this questionnaire have asked?**

This seems thorough enough.

Please check our findings.

**Comment by samuelweiler** [comment]
@willcassella, thank you for doing the self-review.  It looks like you're asking for review of just this one feature, not the whole doc, right?

Before assigning a security reviewer, why is there not an in-line security considerations section (and also a privacy considerations section)?  Both the security reviewers and PING, as the privacy reviewers, expect that prerequisite work to have happened before we do reviews except in certain very early stage reviews.  Since this doc seems to have gone to CR before, those sections should be written.

https://www.w3.org/Guide/documentreview/#how_to_get_horizontal_review
https://www.w3.org/TR/security-privacy-questionnaire/#reviews
