### ISSUE TITLE
Web Neural Network API 2022-03-25 > 2022-06-30

### ISSUE THREAD

**Issue by anssiko** [w3c/security-request#22]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Web Neural Network API
- URL of spec: https://www.w3.org/TR/webnn/

- Does your document have an in-line Security Considerations section, separate from Privacy Considerations?
  - yes, see [Security Considerations](https://www.w3.org/TR/webnn/#security)
- What and when is your next expected transition?
  - We expect to transition to CR by the end of 2022
- What has changed since any previous review?
  - This is the first security review request in this repo. The specification has received [Chrome security team review](https://github.com/webmachinelearning/webnn/issues/241) during 12/2021-03/2022 and this review feedback has been incorporated into [Security Considerations](https://www.w3.org/TR/webnn/#security)
- Please point to the results of your own self-review:
  - [questionnaire responses](https://github.com/webmachinelearning/webnn/blob/main/security-privacy.md) and [discussion](https://github.com/webmachinelearning/webnn/issues/119)
- Where and how to file issues arising?
  - [w3c/webnn issues](https://github.com/webmachinelearning/webnn/issues)
- Pointer to any explainer for the spec?
  - [explainer](https://github.com/webmachinelearning/webnn/blob/main/explainer.md)

Other comments:

- The group is working to address the in-line issues noted in the [Security Considerations](https://www.w3.org/TR/webnn/#security) and address the [security-tracker](https://github.com/webmachinelearning/webnn/issues?q=label%3Asecurity-tracker+) issues well ahead the expected CR transition

**Comment by anssiko** [comment]
@samuelweiler FYI, if helpful to security reviewers, I'm happy to put this topic on the WebML WG's agenda and invite security reviewers to attend as guests. We meet bi-weekly 04:00-05:00 UTC. We're also totally fine with the usual file issues to GH approach. Just wanted to offer an alternative option if whoever will be reviewing this would prefer synchronous interaction over GH.

**Comment by anssiko** [comment]
@samuelweiler, given there has been adequate time for review and no further questions, I assume we can consider this review completed.

As said in the initial request, this specification received substantial review from Chrome Security team during 12/2021-03/2022 that resulted in improved [Security Considerations](https://www.w3.org/TR/webnn/#security) section. The WG decided to prominently surface related open issues in this section and is working toward solutions to these remaining issues.

**Comment by samuelweiler** [comment]
That's fine, yes.

**Comment by anssiko** [comment]
@samuelweiler thank you for confirming the security review of the WebNN API has been completed. The WG's wide review tracker https://github.com/webmachinelearning/webnn/issues/239 has been updated accordingly. Should any further feedback arise out of this review cycle, we welcome feedback via the GH repo issues.

**Comment by anssiko** [comment]
NB: I'm piggypacking on this issue to retain context rather than opening a new issue.

We're looking to publish a new CR Snapshot of the [Web Neural Network API](https://www.w3.org/TR/webnn/) in Q1'24 and wanted to give you a heads up with the following high-level summary of changes for your information and review:

>Since the [initial Candidate Recommendation Snapshot](https://www.w3.org/TR/2023/CR-webnn-20230330/) the Working Group has gathered further [implementation experience](https://webmachinelearning.github.io/webnn-status/) and added new operations and data types needed for well-known [transformers to support generative AI use cases](https://github.com/webmachinelearning/webnn/issues/375). In addition, the group has removed select features informed by this implementation experience: higher-level operations that can be expressed in terms of lower-level primitives in a performant manner, and support for synchronous execution. The group has also updated the specification to use modern authoring conventions to improve interoperability and precision of normative definitions and is developing a new feature, a [backend-agnostic storage type](https://github.com/webmachinelearning/webnn/issues/482), to improve performance and interoperability between the WebNN, WebGPU APIs and purpose-built hardware for ML.

Relevant to this security review forum, I want to acknowledge the continued, major contributions by the Chrome Security team in reviewing the cross-platform and cross-backend implementation of this API. This has resulted in hardening of the normative spec language around operations to guide implementers. We welcome any feedback from people watching this repo and welcome you to join the Web Machine Learning WG if you're interested in contributing to this API concretely.
