### ISSUE TITLE
VISS 2 Core and Transport 2022-08-31 > 2022-09-30

### ISSUE THREAD

**Issue by caribouW3** [w3c/security-request#39]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed:
VISS 2 Core, VISS 2 Transport

- URL of spec:
https://www.w3.org/TR/viss2-core/
https://www.w3.org/TR/viss2-transport/

- What and when is your next expected transition?
End of september

- What has changed since any previous review?
no previous review available

- Does your document have a Security Considerations section?
yes, https://www.w3.org/TR/viss2-core/#security

- Please point to the results of your own self-review
VISS 2 has improved on security and privacy thanks to the access control features of the protocol.
https://www.w3.org/TR/viss2-core/#access-control-model

- Where and how to file issues arising?
https://github.com/w3c/automotive

- Pointer to any explainer for the spec?
https://github.com/w3c/automotive/blob/gh-pages/viss2-explainer.md

Other comments:

Thanks!

**Comment by samuelweiler** [comment]
As in https://github.com/w3c/automotive/issues/464 and as raised by the TAG in https://github.com/w3ctag/design-reviews/issues/768#issuecomment-1283597164, I don't think we can do a complete review at this time.

I have, though, asked both Justin Richer and Mike Jones to look at the authorization scheme defined here.
