### ISSUE TITLE
Guidance on Applying WCAG 2 to Non-Web Information and Communications Technologies (WCAG2ICT) 2024-07-02 > 2024-08-06

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/security-request#72]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Guidance on Applying WCAG 2 to Non-Web Information and Communications Technologies (WCAG2ICT) 
- URL of spec: [This must be a dated version in the TR namespace, not an editor's draft.] https://www.w3.org/TR/2024/DNOTE-wcag2ict-22-20240702/

- Current Rec/Note phase? Draft Note
- What and when is your next expected transition? Publish as a W3C Group Note after review period finishes  (6 August)
- What has changed since any previous review? Updates since the 15 August 2023 draft include:
  * Added guidance for WCAG 2.2 success criteria
  * Addressed comments from the previous draft
  * Completed the Success Criteria Problematic for Closed Functionality section
- Please point to the results of your [self-review](https://w3ctag.github.io/security-questionnaire/)
- Where and how to file issues arising? https://github.com/w3c/wcag2ict/issues
- Pointer to any explainer for the spec?https://www.w3.org/WAI/standards-guidelines/wcag/non-web-ict/

Other comments:

**Comment by simoneonofri** [comment]
comments here https://github.com/w3c/security-request/issues/72
