### ISSUE TITLE
Accessibility Conformance Testing (ACT) Rules Format 1.1 2024-07-24

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/security-request#73]
Accessibility Conformance Testing (ACT) Rules Format 1.1 2024-07-24

We prefers groups to run a self-review around the time of FPWD. See https://w3ctag.github.io/security-questionnaire/.

If you still want us to review your spec, please provide the information below.

In the issue title above add the document name followed by the date of this request.

- name of spec to be reviewed: Accessibility Conformance Testing (ACT) Rules Format 1.1 2024-07-24
- URL of spec: https://www.w3.org/TR/2024/WD-act-rules-format-1.1-20240618/

- Does your document have an in-line Security Considerations section, ideally one separate from the Privacy Considerations? If not, corrrect that before proceeding further. No, but the group is aware of this and is working on it.
- Do you need a reply by a particular date? No, ideally in two months from now
- Please point to the results of your own self-review
    https://github.com/w3c/wcag-act/discussions/578
- Where and how to file issues arising? https://www.github.com/w3c/wcag-act/issues/new
- Pointer to any explainer for the spec? https://www.w3.org/WAI/standards-guidelines/act/

Other comments:

**Comment by simoneonofri** [comment]
I agree with what you wrote in the considerations.

In the next review, we can consider whether a threat model exists for this type of specification.
